Timezone aware sheduling of Alarms
FossifyOrg/Clock pull request #99
Opened 2024-10-28 10:04 UTC by Joshix-1

#### What is it?
- [x] Bugfix
- [ ] Feature
- [ ] Codebase improvement

#### Description of the changes in your PR

- Fix sheduling of next alarms

#### Before/After Screenshots/Screen Record

- Before:
- After:

#### Fixes the following issue(s)

- Fixes #61

#### Relies on the following changes

- 

#### Acknowledgement
- [ ] I read the [contribution guidelines](https://github.com/FossifyOrg/Clock/blob/master/CONTRIBUTING.md).

2024-11-13 19:59 UTC, Joshix-1 commented
I've been using this now for a while and i didn't encounter any issues.
`./gradlew assemble` just works and produces a working apk.

`./gradlew build` complains about the version of a dependency

<note>

```
./gradlew build
> Task :app:lintReportCoreDebug
Wrote HTML report to file:///home/josh/code/FossifyClock/app/build/reports/lint-results-coreDebug.html

> Task :app:lintCoreDebug FAILED
Lint found 21 errors, 0 warnings (140 errors, 1 warning filtered by baseline lint-baseline.xml). First failure:

/home/josh/code/FossifyClock/gradle/libs.versions.toml:28: Error: A newer version of com.android.application than 8.3.1 is available: 8.7.2. (There is also a newer version of 8.3.𝑥 available, if upgrading to 8.7.2 is difficult: 8.3.2) [AndroidGradlePluginVersion]

The full lint text report is located at:
  /home/josh/code/FossifyClock/app/build/intermediates/lint_intermediate_text_report/coreDebug/lintReportCoreDebug/lint-results-coreDebug.txt

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:lintCoreDebug'.
> Lint found errors in the project; aborting build.
  
  Fix the issues identified by lint, or add the issues to the lint baseline via `gradlew updateLintBaseline`.
  For more details, see https://developer.android.com/studio/write/lint#snapshot
  
  Lint found 21 errors, 0 warnings (140 errors, 1 warning filtered by baseline lint-baseline.xml). First failure:
  
  /home/josh/code/FossifyClock/gradle/libs.versions.toml:28: Error: A newer version of com.android.application than 8.3.1 is available: 8.7.2. (There is also a newer version of 8.3.𝑥 available, if upgrading to 8.7.2 is difficult: 8.3.2) [AndroidGradlePluginVersion]
  
  The full lint text report is located at:
    /home/josh/code/FossifyClock/app/build/intermediates/lint_intermediate_text_report/coreDebug/lintReportCoreDebug/lint-results-coreDebug.txt

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

BUILD FAILED in 12s
259 actionable tasks: 5 executed, 254 up-to-date
```
</note>

2024-11-18 14:15 UTC, naveensingh commented
Clock is to be updated in the coming weeks, I'll check it out then.

2024-11-19 07:21 UTC, Joshix-1 commented
I don't know how #73 happened, but this pr should fix it.

2025-03-09 00:30 UTC, naveensingh requested changes

2025-03-09 11:32 UTC, Joshix-1 commented on app/src/main/kotlin/org/fossify/clock/extensions/Context.kt
> +fun Context.setupAlarmClock(alarm: Alarm, triggerTime: Calendar) {
That would lead to every caller having to convert the Calendar themselves.
With Calendar the unit is implicit in the type. With a long parameter it's only in the name.

2025-03-09 11:38 UTC, naveensingh commented on app/src/main/kotlin/org/fossify/clock/extensions/Context.kt
> +fun Context.setupAlarmClock(alarm: Alarm, triggerTime: Calendar) {
Yes. The function shouldn't have access to the whole object, being explicit is always a good idea.

2025-03-09 11:42 UTC, Joshix-1 commented on app/src/main/kotlin/org/fossify/clock/extensions/Context.kt
> +fun Context.setupAlarmClock(alarm: Alarm, triggerTime: Calendar) {
i really do not like it when units aren't part of the type system. That leaves so much room for errors

2025-03-09 12:19 UTC, naveensingh commented on app/src/main/kotlin/org/fossify/clock/extensions/Context.kt
> +fun Context.setupAlarmClock(alarm: Alarm, triggerTime: Calendar) {
Well, representing time using numbers is pretty common :)

2025-03-09 12:23 UTC, Joshix-1 commented on app/src/main/kotlin/org/fossify/clock/extensions/Context.kt
> +fun Context.setupAlarmClock(alarm: Alarm, triggerTime: Calendar) {
Never with just a number :)
You always also need a unit (even if it's implicit)

2025-03-09 19:55 UTC, naveensingh commented
I tested this a couple times on a couple devices and it works :tada:

I discovered that sometimes the alarms won't trigger when date-time is manually changed in system settings but that is out of scope for this PR.

Thank you!

2025-03-09 19:55 UTC, merged